---
- name: Crea Imagen de Contenedor
  hosts: podman
#  connection: local
  gather_facts: false
  become: true

  vars_files:
    - ../variables.yaml

  tasks:
  - name: Clona Repositorio Git
    ansible.builtin.git:
      repo: "{{ url_git }}"
      dest: "{{ nombre_repo }}"

  - name: Podman Login
    shell: 'podman login -u {{ usuario_oci }} -p "{{ token }}" {{ registry_url }}'


  - name: Build Imagen de Contenedor
    shell: "podman build --tag ci-app {{ nombre_repo }}/"

  - name: Tag Imagen
    shell: "podman tag localhost/ci-app:latest {{ registry_url }}/{{ namespace_repo }}/ci-app:latest"

  - name: Push Imagen
    shell: "podman push {{ registry_url }}/{{ namespace_repo }}/ci-app:latest"
